User.create(username: 'jennifer', password: 'a')
User.create(username: 'michael', password: 'b')
User.create(username: 'mary', password: 'c')
User.create(username: 'abdulla', password: 'd')
User.create(username: 'sara', password: 'e')
Todo.create(name: 'yoga class', url: 'https://www.yogafinder.com/')
Todo.create(name: 'make a kale smoothie', url: 'https://www.wellplated.com/kale-pineapple-smoothie/')
Todo.create(name: 'write a haiku', url: 'https://www.creative-writing-now.com/how-to-write-a-haiku.html')
Todo.create(name: 'start Game of Thrones', url: 'http://www.digitalspy.com/tv/game-of-thrones/feature/a827753/game-of-thrones-dictionary/')
Todo.create(name: 'learn how to change a car tire', url: 'https://www.bridgestonetire.com/tread-and-trend/drivers-ed/how-to-change-a-flat-tire')
Todo.create(name: 'scubadive', url: 'https://www.scubadiving.com/')
Todo.create(name: 'skinny dip', url: 'https://www.fourseasons.com/magazine/discover/night-swimming-around-the-world/')
Todo.create(name: 'meditation', url: 'https://www.headspace.com/')
Todo.create(name: 'laser tag', url: 'https://www.timeout.com/new-york-kids/things-to-do/the-best-laser-tag-in-nyc')
Todo.create(name: 'go to lunch with a new coworker', url: 'https://www.entrepreneur.com/article/249372')
Wishlist.create(user_id: 1, todo_id: 2)
Wishlist.create(user_id: 1, todo_id: 3)
Wishlist.create(user_id: 1, todo_id: 6)
Wishlist.create(user_id: 2, todo_id: 10)
Wishlist.create(user_id: 2, todo_id: 8)
Wishlist.create(user_id: 2, todo_id: 6)
Wishlist.create(user_id: 3, todo_id: 3)
Wishlist.create(user_id: 3, todo_id: 9)
Wishlist.create(user_id: 3, todo_id: 5)
Wishlist.create(user_id: 4, todo_id: 2)
Wishlist.create(user_id: 4, todo_id: 9)
Wishlist.create(user_id: 4, todo_id: 10)
Wishlist.create(user_id: 5, todo_id: 3)
Wishlist.create(user_id: 5, todo_id: 4)
Wishlist.create(user_id: 5, todo_id: 5)
Complete.create(user_id: 1, todo_id: 1, date: '2018-03-01')
Complete.create(user_id: 1, todo_id: 7, date: '2018-03-02')
Complete.create(user_id: 1, todo_id: 8, date: '2018-03-03')
Complete.create(user_id: 2, todo_id: 9, date: '2018-03-04')
Complete.create(user_id: 2, todo_id: 7, date: '2018-03-05')
Complete.create(user_id: 2, todo_id: 5, date: '2018-04-01')
Complete.create(user_id: 3, todo_id: 7, date: '2018-04-02')
Complete.create(user_id: 3, todo_id: 2, date: '2018-04-07')
Complete.create(user_id: 3, todo_id: 6, date: '2018-03-10')
Complete.create(user_id: 4, todo_id: 1, date: '2018-03-11')
Complete.create(user_id: 4, todo_id: 6, date: '2018-03-12')
Complete.create(user_id: 4, todo_id: 3, date: '2018-03-13')
Complete.create(user_id: 5, todo_id: 6, date: '2018-03-14')
Complete.create(user_id: 5, todo_id: 7, date: '2018-03-15')
Complete.create(user_id: 5, todo_id: 8, date: '2018-03-16')
