User.create(username: 'jennifer', password: 'a')
User.create(username: 'michael', password: 'b')
User.create(username: 'mary', password: 'c')
User.create(username: 'jason', password: 'd')
User.create(username: 'sara', password: 'e')
Todo.create(name: 'yoga', url: 'website1')
Todo.create(name: 'sagrada famiglia', url: 'website2')
Todo.create(name: 'barcelona', url: 'website3')
Todo.create(name: 'lisbon', url: 'website4')
Todo.create(name: 'berlin', url: 'website5')
Todo.create(name: 'florence', url: 'website6')
Todo.create(name: 'switzerland', url: 'website7')
Todo.create(name: 'make pretzels', url: 'website8')
Todo.create(name: 'fall in love', url: 'website9')
Todo.create(name: 'salsa dance', url: 'website10')
Wishlist.create(user_id: 1, todo_id: 2)
Wishlist.create(user_id: 1, todo_id: 3)
Wishlist.create(user_id: 1, todo_id: 6)
Wishlist.create(user_id: 2, todo_id: 10)
Wishlist.create(user_id: 2, todo_id: 8)
Wishlist.create(user_id: 2, todo_id: 6)
Wishlist.create(user_id: 3, todo_id: 3)
Wishlist.create(user_id: 3, todo_id: 9)
Wishlist.create(user_id: 3, todo_id: 5)
Wishlist.create(user_id: 4, todo_id: 2)
Wishlist.create(user_id: 4, todo_id: 9)
Wishlist.create(user_id: 4, todo_id: 10)
Wishlist.create(user_id: 5, todo_id: 3)
Wishlist.create(user_id: 5, todo_id: 4)
Wishlist.create(user_id: 5, todo_id: 5)
Complete.create(user_id: 1, todo_id: 1, date: '2018-03-01')
Complete.create(user_id: 1, todo_id: 7, date: '2018-03-02')
Complete.create(user_id: 1, todo_id: 8, date: '2018-03-03')
Complete.create(user_id: 2, todo_id: 9, date: '2018-03-04')
Complete.create(user_id: 2, todo_id: 7, date: '2018-03-05')
Complete.create(user_id: 2, todo_id: 5, date: '2018-04-01')
Complete.create(user_id: 3, todo_id: 7, date: '2018-04-02')
Complete.create(user_id: 3, todo_id: 2, date: '2018-04-07')
Complete.create(user_id: 3, todo_id: 6, date: '2018-03-10')
Complete.create(user_id: 4, todo_id: 1, date: '2018-03-11')
Complete.create(user_id: 4, todo_id: 6, date: '2018-03-12')
Complete.create(user_id: 4, todo_id: 3, date: '2018-03-13')
Complete.create(user_id: 5, todo_id: 6, date: '2018-03-14')
Complete.create(user_id: 5, todo_id: 7, date: '2018-03-15')
Complete.create(user_id: 5, todo_id: 8, date: '2018-03-16')
